config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'welcome#index'
  
  get 'my_portfolio', to: 'users#my_portfolio'
  
  get 'search_stocks', to: 'stocks#search'

end

app/models/stock.rb
class Stock < ActiveRecord::Base
    
    def self.find_by_ticker(ticker_symbol)
        where(ticker: ticker_symbol).first
    end
    
    def self.new_from_lookup(ticker_symbol)
        looked_up_stock = StockQuote::Stock.quote(ticker_symbol)
        return nil unless looked_up_stock.name
        
        new_stock = new(ticker:looked_up_stock.symbol, name:looked_up_stock.name)
        new_stock.last_price = new_stock.price
        new_stock
    end
    
    def price
        closing_price = StockQuote::Stock.quote(ticker).close
        return "#{closing_price} (Closing)" if closing_price 
        
        opening_price = StockQuote::Stock.quote(ticker).open
        return "#{opening_price} (Opening)" if opening_price
        'Unavailable'
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  
  def search
    if params[:stock]
      @stock = Stock.find_by_ticker(params[:stock])
      @stock ||= Stock.new_from_lookup(params[:stock])
    end
    
    if @stock
      #render json: @stock
      render partial: 'lookup'
    else
      render status: :not_found, nothing:true
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "MyWallstreet" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">MyWallstreet</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>

      <footer>
        <p>&copy; Company 2017</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/stocks/_lookup.html.erb
<div id="stock_lookup">
    
  <h3>Search for Stocks</h3>
  <%= form_tag search_stocks_path, remote:true, method: :get, id:'stock-lookup-form' do %>
  <div class="form-group row no-padding text-center col-md-12">
    <div class="col-md-10">
      <%= text_field_tag :stock, params[:stock], placeholder:'Stock Ticker Symbol', autofocus:true, 
                                                    class: 'form-control search-box input-lg' %>
    </div>
    <div class="col-md-2">
      <%= button_tag(type: :submit, class: "btn btn-lg btn-success") do %>
        <i class= "fa fa-search"></i> Look up a stock
      <% end %>
    </div>
  </div>
  <% end %>
  <% if @stock %>
    <div id="stock_lookup_results" class="well results-block">
        <strong>Symbol:</strong> <%= @stock.ticker %>
        <strong>Name:</strong> <%= @stock.name %>
        <strong>Price:</strong> <%= @stock.price %>
    </div>
  <% end %>
</div>

app/views/stocks/search.html.erb
<h1>Stocks#search</h1>
<p>Find me in app/views/stocks/search.html.erb</p>

app/views/users/my_portfolio.html.erb
<%= render 'stocks/lookup' %>

app/views/welcome/index.html.erb
<h1>myWallstreet</h1>

<%= link_to "logout, destroy_user_session_path, method::delete" %>